# Unique project identifier
sonar.projectKey=simple_django_app
sonar.projectName=Simple Django App
sonar.projectVersion=1.0

# Path to the source code (relative to workspace root)
sonar.sources=.
sonar.language=py
sonar.python.version=3.12.3

# CRITICAL: Exclusions
# This prevents SonarQube from scanning 100,000 lines of library code in venv
sonar.exclusions=**/venv/**, **/env/**, **/migrations/**, **/static/**, manage.py, db.sqlite3, .jenkins/**